# Video game bingo

c("Pokemon Go",
  "Borderlands 2",
  "Divinity: Original Sin2",
  "Dishonored",
  "Final Fantasy VII",
  "Assassin's Creed IV: Black Flag",
  "Monkey Island 2",
  "Burnout 3: Takedown",
  "Fallout 2",
  "Undertable",
  "League of Legends",
  "Mega Man 3",
  "Soulcalibur",
  "Thief II: The Metal Age",
  "SimCity 2000",
  "Inside",
  "Contra",
  "Tony Hawk's Pro Skater 2",
  "Monster Hunter: World",
  "Resident Evil 2",
  "System Shock 2",
  "Grand Theft Auto",
  "Persona 5",
  "Fortnite",
  "Fable 2",
  "GoldenEye 007",
  "Suikoden II",
  "Doat 2",
  "The Sims")
